language: python
python:
    - "3.5"
# command to run tests
before_script:
    - pip install coveralls
script:
    - python3 test_rpn.py test c4cs-rpn
    - coverage run --source=c4cs-rpn test_rpn.py test c4cs-rpn
after_success: coveralls
